version: "2"

services:
################ LAMP Stack.
  
# Requires mariadb container.        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - '82:80'
    networks:
      internal:
      shared:
        ipv4_address: 172.55.0.9
        
  adminer:
    image: adminer
    links:
      - mariadb
      - postgres
      - mongo
    depends_on:
      - mariadb
      - postgres
      - mongo
    ports:
      #- '83:80'
      - '83:8080'
    restart: always
    networks:
      internal:
      shared:
        ipv4_address: 172.55.0.10

################ Database images.

  # redis:
  #   image: redis:alpine
  #   networks:
  #     - internal

  # memcached:
  #   image: memcached:alpine
  #   networks:
  #     - internal

################ Selenium image configuration and php-fpm-data as proxy container for selenium.
  # php-fpm-data:
  #   image: lordius/alpine-php_fpm
  #   networks:
  #     - internal

  # selenium:
  #   image: selenium/standalone-firefox-debug:2.48.2
  #   links:
  #     - php-fpm
  #   ports:
  #     - "4444"
  #     - "5900"
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   networks:
  #     shared:
  #       ipv4_address: 172.55.0.11
